option(VK_BUILD_TESTS "Build Vaulkeeper test suite" ON)
option(VK_BUILD_BENCHMARKS "Build Vaulkeeper micro benchmarks" OFF)
option(VK_BUILD_INSTALLER "Build MSI installer via WiX" OFF)
option(VK_ENABLE_LTO "Enable link time optimization" ON)
option(VK_ENABLE_PGO_GENERATE "Instrument binary for profile guided optimization" OFF)
option(VK_ENABLE_PGO_USE "Use collected PGO profile data" OFF)
option(VK_ENABLE_ASAN "Enable address sanitizer" OFF)
option(VK_ENABLE_UBSAN "Enable undefined behavior sanitizer" OFF)
option(VK_STRICT_WARNINGS "Treat warnings as errors" ON)
option(VK_USE_MIMALLOC "Override default allocator with mimalloc" ON)
option(VK_USE_TBB "Use Intel TBB parallel algorithms" ON)

set(VK_TELEMETRY_ENDPOINT "" CACHE STRING "Optional telemetry endpoint. Empty disables all network traffic.")
set(VK_CODE_SIGNING_THUMBPRINT "" CACHE STRING "Authenticode certificate thumbprint for signed release builds.")
set(VK_WINDOWS_MIN_VERSION "0x0A00" CACHE STRING "Minimum supported Windows version, default Windows 10.")

if(VK_ENABLE_PGO_GENERATE AND VK_ENABLE_PGO_USE)
    message(FATAL_ERROR "VK_ENABLE_PGO_GENERATE and VK_ENABLE_PGO_USE cannot both be enabled. Pick one phase.")
endif()
